from pinecone import Pinecone
import math
import os
import re
from collections import Counter
from dotenv import load_dotenv
from typing import Dict, List, Tuple

load_dotenv()

# Embeddings are generated by Pinecone's integrated model (llama-text-embed-v2)
# during upsert_records and search. OpenAI embedding is no longer used.

pinecone_client = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
index = pinecone_client.Index(os.getenv("PINECONE_INDEX_NAME"))

# Must match the index field_map (typically field_map={"text": "chunk_text"}).
TEXT_FIELD = "chunk_text"

# BM25 defaults (Robertson / TREC). k1 controls term-frequency saturation;
# b controls how much long documents are down-weighted.
_BM25_K1 = 1.5
_BM25_B = 0.75
# Reciprocal Rank Fusion constant. 60 is the value from Cormack et al.
_RRF_K = 60
_TOKEN = re.compile(r"[a-z0-9_]+")


def _namespace(namespace: str) -> str:
    return namespace if namespace else "__default__"


def store_in_pinecone(chunks: List[str], namespace: str = ""):
    records = []
    for i, chunk in enumerate(chunks):
        records.append({
            "_id": f"chunk_{i}",
            TEXT_FIELD: chunk,
            "chunk_index": i,
            "category": "source markdown document.md",
        })

    batch_size = 96
    ns = _namespace(namespace)
    for i in range(0, len(records), batch_size):
        batch = records[i:i + batch_size]
        index.upsert_records(namespace=ns, records=batch)


def search_in_pinecone(query: str, top_k: int = 5, namespace: str = ""):
    """Dense semantic search only (llama-text-embed-v2 via Pinecone)."""
    ranked = _semantic_rank(query, top_k=top_k, namespace=namespace)
    print(f"Found {len(ranked)} matches for the query.")
    return [text for _, text in ranked]


def hybrid_search_in_pinecone(query: str, top_k: int = 5, namespace: str = ""):
    """Semantic search plus BM25 keyword search, merged with RRF.

    Pinecone's integrated dense index cannot store sparse BM25 vectors, so
    keyword ranking runs on the chunk texts fetched from the same namespace.
    Reciprocal Rank Fusion then combines the two ranked lists without needing
    to rescale cosine scores against BM25 scores.
    """
    semantic = _semantic_rank(query, top_k=top_k * 4, namespace=namespace)
    keyword = _bm25_rank(query, namespace=namespace)

    merged = _reciprocal_rank_fusion([semantic, keyword], top_k=top_k)
    print(
        f"Hybrid search: {len(semantic)} semantic + {len(keyword)} BM25 "
        f"-> {len(merged)} fused matches."
    )
    return [text for _, text in merged]


def _semantic_rank(query: str, top_k: int, namespace: str) -> List[Tuple[str, str]]:
    results = index.search(
        namespace=_namespace(namespace),
        query={
            "inputs": {"text": query},
            "top_k": top_k,
        },
        fields=[TEXT_FIELD],
    )
    ranked: List[Tuple[str, str]] = []
    for hit in _hits(results):
        record_id = _attr(hit, "id", "_id") or f"sem_{len(ranked)}"
        ranked.append((str(record_id), _text_from_mapping(_attr(hit, "fields") or {})))
    return ranked


def _bm25_rank(query: str, namespace: str) -> List[Tuple[str, str]]:
    corpus = _load_corpus(namespace)
    if not corpus:
        return []

    docs = {record_id: _tokenize(text) for record_id, text in corpus.items()}
    query_tokens = _tokenize(query)
    if not query_tokens:
        return []

    n_docs = len(docs)
    avg_len = sum(len(tokens) for tokens in docs.values()) / n_docs
    df = Counter(token for tokens in docs.values() for token in set(tokens))

    scored: List[Tuple[float, str]] = []
    for record_id, tokens in docs.items():
        tf = Counter(tokens)
        doc_len = len(tokens) or 1
        score = 0.0
        for term in query_tokens:
            if term not in tf:
                continue
            # Plus-one IDF so rare terms still rank above zero even if they
            # appear in every document.
            idf = math.log((n_docs - df[term] + 0.5) / (df[term] + 0.5) + 1.0)
            freq = tf[term]
            denom = freq + _BM25_K1 * (1 - _BM25_B + _BM25_B * doc_len / avg_len)
            score += idf * (freq * (_BM25_K1 + 1)) / denom
        if score > 0:
            scored.append((score, record_id))

    scored.sort(key=lambda item: item[0], reverse=True)
    return [(record_id, corpus[record_id]) for _, record_id in scored]


def _reciprocal_rank_fusion(
    rankings: List[List[Tuple[str, str]]],
    top_k: int,
) -> List[Tuple[str, str]]:
    texts: Dict[str, str] = {}
    rrf: Dict[str, float] = {}
    for ranking in rankings:
        for rank, (record_id, text) in enumerate(ranking, start=1):
            rrf[record_id] = rrf.get(record_id, 0.0) + 1.0 / (_RRF_K + rank)
            texts.setdefault(record_id, text)

    ordered = sorted(rrf, key=rrf.get, reverse=True)
    return [(record_id, texts[record_id]) for record_id in ordered[:top_k]]


def _load_corpus(namespace: str) -> Dict[str, str]:
    ns = _namespace(namespace)
    ids: List[str] = []
    for page in index.list(namespace=ns):
        for item in getattr(page, "vectors", None) or page or []:
            item_id = _attr(item, "id") if not isinstance(item, str) else item
            if item_id:
                ids.append(str(item_id))

    corpus: Dict[str, str] = {}
    batch_size = 100
    for i in range(0, len(ids), batch_size):
        fetched = index.fetch(ids=ids[i:i + batch_size], namespace=ns)
        vectors = _attr(fetched, "vectors") or {}
        if isinstance(vectors, dict):
            items = vectors.items()
        else:
            items = [( _attr(vec, "id"), vec) for vec in vectors]
        for record_id, vector in items:
            text = _text_from_mapping(_attr(vector, "metadata") or {})
            if text:
                corpus[str(record_id)] = text
    return corpus


def _tokenize(text: str) -> List[str]:
    return _TOKEN.findall(text.lower())


def _hits(results) -> list:
    if hasattr(results, "result") and getattr(results.result, "hits", None) is not None:
        return list(results.result.hits)
    if isinstance(results, dict):
        return (
            results.get("result", {}).get("hits", [])
            or results.get("results", {}).get("hits", [])
        )
    return []


def _attr(obj, *names):
    if obj is None:
        return None
    for name in names:
        if isinstance(obj, dict) and name in obj:
            return obj[name]
        if hasattr(obj, name):
            return getattr(obj, name)
    return None


def _text_from_mapping(fields) -> str:
    if not fields:
        return ""
    if not isinstance(fields, dict):
        fields = dict(fields)
    return fields.get(TEXT_FIELD) or fields.get("text") or ""
